"""
Django settings for FinWeb project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=_5m*%gp6$4ya$3csxtwe_slguyqz!f21ix)sv+0hz*b--rsru'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ ]

# Application definition

INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'app.apps.AppConfig',
  'rest_framework'
]

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FinWeb.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join(BASE_DIR, 'templates')]
    ,
    'APP_DIRS': True,
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'FinWeb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
import django.db.backends.dummy
DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
  }
}

# Self Authenticate Backend
AUTHENTICATION_BACKENDS = ['app.db.mongobackend.MongoBackend']

# Email backend
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.qq.com'
# EMAIL_PORT = 465
# EMAIL_HOST_USER = '237533031@qq.com'
# EMAIL_HOST_PASSWORD = ''
# EMAIL_USE_SSL = True

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = (
  os.path.join(BASE_DIR, 'static'),
)

# MongoDB
MONGO_HOST = "114.212.191.119"  # 主机IP
MONGO_PORT = 27017  # 端口号
MONGO_DBNAME = 'fin_news'
MONGO_COLLECTION_USER = 'users'
MONGO_COLLECTION_WALLSTREET = 'wallstreet'
MONGO_COLLECTION_HEXUN = 'hexun'
MONGO_COLLECTION_SINA_ROLL = 'sina_roll'
MONGO_COLLECTION_TENCENT = 'tencent'
MONGO_COLLECTION_EAST_MONEY_STOCK_LIST = 'east_money_stock_list'
MONGO_COLLECTION_EAST_MONEY_STOCK_MAP_USER = 'east_money_stock_map_user'
MONGO_COLLECTION_EAST_MONEY_STOCK_USER_INFO = 'east_money_stock_user_info'
MONGO_COLLECTION_EAST_MONEY_ARTICLE = 'east_money_article'
MONGO_COLLECTION_EAST_MONEY_ANNO = 'east_money_anno'
MONGO_COLLECTION_EAST_MONEY_RESEARCH_REPORT = 'east_money_research_report'
MONGO_COLLECTION_CANDIDATE = 'candidate'

# Django-Rest-Framework
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

WORD_VEC_MODEL = 'wv.model'
WORD_VEC_DIM = 128